export const UPDATE_PATIENTS = "UPDATE_PATIENTS";

//login user

export const LOGIN_START = "LOGIN_START";
export const LOGIN_DOCTOR = "LOGIN_DOCTOR";
export const AUTHENTICATE_DOCTOR = "AUTHENTICATE_DOCTOR";
export const LOG_OUT = "LOG_OUT";

export const SIGNUP_SUCCESSFULL = "SIGNUP_SUCCESSFULL";

//Doctor profile

export const PATIENT_PROFILE_SUCCESS = "PATIENT_PROFILE_SUCCESS";
export const FETCH_PATIENT_PROFILE = "FETCH_PATIENT_PROFILE";
export const ADDING_NEW_PATIENT = "ADDING_NEW_PATIENT";
export const CREATE_REPORT_SUCCESSFULL = "CREATE_REPORT_SUCCESSFULL";
